import { Recruiter } from "@/pages/MainHomePage/PastRcruiter";

export const recruiters: Recruiter[] = [
  {
    id: 1,
    name: "GNFC",
    logo: "/images/GNFC.png",
    infoLink: "/recruiters/techcorp",
  },
  {
    id: 2,
    name: "MICRON",
    logo: "/images/MICRON.png",
    infoLink: "/recruiters/techcorp",
  },
  {
    id: 3,
    name: "RELIANCE",
    logo: "/images/RELIANCE.png",
    infoLink: "/recruiters/techcorp",
  },
  {
    id: 4,
    name: "L&T",
    logo: "/images/L&T.png",
    infoLink: "/recruiters/techcorp",
  },
  {
    id: 5,
    name: "ADANI",
    logo: "/images/ADANI.png",
    infoLink: "/recruiters/techcorp",
  },
  {
    id: 6,
    name: "TECH MAHINDRA",
    logo: "/images/TECH_MAHINDRA.png",
    infoLink: "/recruiters/techcorp",
  },
  {
    id: 7,
    name: "AARTI INDUSTRIES",
    logo: "/images/AARTI_INDUSTRIES.png",
    infoLink: "/recruiters/techcorp",
  },
  {
    id: 8,
    name: "HITACHI",
    logo: "/images/HITACHI.png",
    infoLink: "/recruiters/techcorp",
  },
  {
    id: 9,
    name: "TORRENT POWER",
    logo: "/images/TORRENT_POWER.png",
    infoLink: "/recruiters/techcorp",
  },
  {
    id: 10,
    name: "ATUL",
    logo: "/images/ATUL.png",
    infoLink: "/recruiters/techcorp",
  },
  {
    id: 11,
    name: "UPL",
    logo: "/images/UPL.png",
    infoLink: "/recruiters/techcorp",
  },
  {
    id: 12,
    name: "VIMAL",
    logo: "/images/VIMAL.png",
    infoLink: "/recruiters/techcorp",
  },
  {
    id: 13,
    name: "TATA",
    logo: "/images/TATA.png",
    infoLink: "/recruiters/techcorp",
  },
  {
    id: 14,
    name: "INFOSYS",
    logo: "/images/INFOSYS.png",
    infoLink: "/recruiters/techcorp",
  },
  {
    id: 15,
    name: "AIR PRODUCTS",
    logo: "/images/AIR_PRODUCTS.png",
    infoLink: "/recruiters/techcorp",
  },
  {
    id: 16,
    name: "AMUL",
    logo: "/images/AMUL.png",
    infoLink: "/recruiters/techcorp",
  },
  {
    id: 17,
    name: "ZEUS",
    logo: "/images/ZEUS.png",
    infoLink: "/recruiters/techcorp",
  },
  {
    id: 18,
    name: "ZURU",
    logo: "/images/ZURU.png",
    infoLink: "/recruiters/techcorp",
  },
  {
    id: 19,
    name: "ZYDUS",
    logo: "/images/ZYDUS.png",
    infoLink: "/recruiters/techcorp",
  },
  {
    id: 20,
    name: "TATA CHEMICAL",
    logo: "/images/TATA_CHEMICAL.png",
    infoLink: "/recruiters/techcorp",
  },
  {
    id: 21,
    name: "ACCENTURE",
    logo: "/images/ACCENTURE.png",
    infoLink: "/recruiters/techcorp",
  },

  {
    id: 22,
    name: "TCS",
    logo: "/images/TCS.png",
    infoLink: "/recruiters/techcorp",
  },
  {
    id: 23,
    name: "GODREJ",
    logo: "/images/GODREJ.png",
    infoLink: "/recruiters/techcorp",
  },
  {
    id: 24,
    name: "ADITYA BIRLA",
    logo: "/images/ADITYA_BIRLA.png",
    infoLink: "/recruiters/techcorp",
  },
  {
    id: 25,
    name: "IBM",
    logo: "/images/IBM.png",
    infoLink: "/recruiters/techcorp",
  },
  {
    id: 26,
    name: "BACANCY",
    logo: "/images/BACANCY.png",
    infoLink: "/recruiters/techcorp",
  },
  {
    id: 27,
    name: "WORLEY",
    logo: "/images/WORLEY.png",
    infoLink: "/recruiters/techcorp",
  },
  {
    id: 28,
    name: "BKT",
    logo: "/images/BKT.png",
    infoLink: "/recruiters/techcorp",
  },
  {
    id: 29,
    name: "ARGUSOFT",
    logo: "/images/ARGUSOFT.png",
    infoLink: "/recruiters/techcorp",
  },
  {
    id: 30,
    name: "ARVIND",
    logo: "/images/ARVIND.png",
    infoLink: "/recruiters/techcorp",
  },
  {
    id: 31,
    name: "NAYARA",
    logo: "/images/NAYARA.png",
    infoLink: "/recruiters/techcorp",
  },
  {
    id: 32,
    name: "ARAYMOND",
    logo: "/images/ARAYMOND.png",
    infoLink: "/recruiters/techcorp",
  },
  {
    id: 33,
    name: "AMNS",
    logo: "/images/AMNS.png",
    infoLink: "/recruiters/techcorp",
  },
  {
    id: 34,
    name: "YOKOGAWA",
    logo: "/images/YOKOGAWA.png",
    infoLink: "/recruiters/techcorp",
  },
  {
    id: 35,
    name: "ANALOG DEVICES",
    logo: "/images/ANALOG_DEVICES.png",
    infoLink: "/recruiters/techcorp",
  },
  {
    id: 36,
    name: "DCM SHREE RAM",
    logo: "/images/DCM_SHREE_RAM.png",
    infoLink: "/recruiters/techcorp",
  },
  {
    id: 37,
    name: "AMI POLYMER",
    logo: "/images/AMI_POLYMER.png",
    infoLink: "/recruiters/techcorp",
  },
  {
    id: 38,
    name: "ADVET E MODAL",
    logo: "/images/ADVET_E_MODAL.png",
    infoLink: "/recruiters/techcorp",
  },
  {
    id: 40,
    name: "CEAT",
    logo: "/images/CEAT.png",
    infoLink: "/recruiters/techcorp",
  },
  {
    id: 41,
    name: "COLORJET",
    logo: "/images/COLORJET.png",
    infoLink: "/recruiters/techcorp",
  },
  {
    id: 42,
    name: "CONGA",
    logo: "/images/CONGA.png",
    infoLink: "/recruiters/techcorp",
  },
  {
    id: 43,
    name: "CREST",
    logo: "/images/CREST.png",
    infoLink: "/recruiters/techcorp",
  },
  {
    id: 44,
    name: "CYBAGE",
    logo: "/images/CYBAGE.png",
    infoLink: "/recruiters/techcorp",
  },
  {
    id: 45,
    name: "AGS HEALTH",
    logo: "/images/AGS_HEALTH.png",
    infoLink: "/recruiters/techcorp",
  },
  {
    id: 46,
    name: "DECIMAL",
    logo: "/images/DECIMAL.png",
    infoLink: "/recruiters/techcorp",
  },
  {
    id: 47,
    name: "DEEPAK",
    logo: "/images/DEEPAK.png",
    infoLink: "/recruiters/techcorp",
  },
  {
    id: 48,
    name: "DEEPAK FERTILISERS",
    logo: "/images/DEEPAK_FERTILISERS.png",
    infoLink: "/recruiters/techcorp",
  },
  {
    id: 49,
    name: "DELOITTE",
    logo: "/images/DELOITTE.png",
    infoLink: "/recruiters/techcorp",
  },
  {
    id: 50,
    name: "ENFOCHIPS",
    logo: "/images/ENFOCHIPS.png",
    infoLink: "/recruiters/techcorp",
  },
  {
    id: 51,
    name: "LINDE",
    logo: "/images/LINDE.png",
    infoLink: "/recruiters/techcorp",
  },
  {
    id: 52,
    name: "RAPIDOPS",
    logo: "/images/RAPIDOPS.png",
    infoLink: "/recruiters/techcorp",
  },
  {
    id: 53,
    name: "GARDEN VARELI",
    logo: "/images/GARDEN_VARELI.png",
    infoLink: "/recruiters/techcorp",
  },
  {
    id: 54,
    name: "NIRMA",
    logo: "/images/NIRMA.png",
    infoLink: "/recruiters/techcorp",
  },
  {
    id: 55,
    name: "ODOO",
    logo: "/images/ODOO.png",
    infoLink: "/recruiters/techcorp",
  },
  {
    id: 56,
    name: "VOLTAS",
    logo: "/images/VOLTAS.png",
    infoLink: "/recruiters/techcorp",
  },

  {
    id: 58,
    name: "GUJARAT GAS",
    logo: "/images/GUJARAT_GAS.png",
    infoLink: "/recruiters/techcorp",
  },
  {
    id: 59,
    name: "HERO HONDA",
    logo: "/images/HERO_HONDA.png",
    infoLink: "/recruiters/techcorp",
  },
  {
    id: 60,
    name: "HEXACODER",
    logo: "/images/HEXACODER.png",
    infoLink: "/recruiters/techcorp",
  },
  {
    id: 61,
    name: "WELSPUN",
    logo: "/images/WELSPUN.png",
    infoLink: "/recruiters/techcorp",
  },
  {
    id: 62,
    name: "HOPSCOTCH",
    logo: "/images/HOPSCOTCH.png",
    infoLink: "/recruiters/techcorp",
  },
  {
    id: 63,
    name: "HSBC",
    logo: "/images/HSBC.png",
    infoLink: "/recruiters/techcorp",
  },

  {
    id: 66,
    name: "INTECH",
    logo: "/images/INTECH.png",
    infoLink: "/recruiters/techcorp",
  },
  {
    id: 67,
    name: "IRM ENERGY",
    logo: "/images/IRM_ENERGY.png",
    infoLink: "/recruiters/techcorp",
  },
  {
    id: 68,
    name: "KEYENCE",
    logo: "/images/KEYENCE.png",
    infoLink: "/recruiters/techcorp",
  },
  {
    id: 69,
    name: "KHS",
    logo: "/images/KHS.png",
    infoLink: "/recruiters/techcorp",
  },
  {
    id: 70,
    name: "KNOCKOUT",
    logo: "/images/KNOCKOUT.png",
    infoLink: "/recruiters/techcorp",
  },
  {
    id: 71,
    name: "KRIBCHO",
    logo: "/images/KRIBCHO.png",
    infoLink: "/recruiters/techcorp",
  },
  {
    id: 73,
    name: "LINDE",
    logo: "/images/LINDE.png",
    infoLink: "/recruiters/techcorp",
  },
  {
    id: 74,
    name: "LOGIC FACTORY",
    logo: "/images/LOGIC_FACTORY.png",
    infoLink: "/recruiters/techcorp",
  },
  {
    id: 75,
    name: "MARUTI TECHLABS",
    logo: "/images/MARUTI_TECHLABS.png",
    infoLink: "/recruiters/techcorp",
  },
  {
    id: 76,
    name: "MEDITAB",
    logo: "/images/MEDITAB.png",
    infoLink: "/recruiters/techcorp",
  },
  {
    id: 77,
    name: "MEHTA GROUP",
    logo: "/images/MEHTA_GROUP.png",
    infoLink: "/recruiters/techcorp",
  },
  {
    id: 78,
    name: "MG",
    logo: "/images/MG.png",
    infoLink: "/recruiters/techcorp",
  },
  {
    id: 79,
    name: "CAIRN",
    logo: "/images/CAIRN.png",
    infoLink: "/recruiters/techcorp",
  },
  {
    id: 80,
    name: "CAPITAL FIRST",
    logo: "/images/CAPITAL_FIRST.png",
    infoLink: "/recruiters/techcorp",
  },
  {
    id: 81,
    name: "GFL",
    logo: "/images/GFL.png",
    infoLink: "/recruiters/techcorp",
  },
  {
    id: 82,
    name: "GHCL",
    logo: "/images/GHCL.png",
    infoLink: "/recruiters/techcorp",
  },
  {
    id: 83,
    name: "PI",
    logo: "/images/PI.png",
    infoLink: "/recruiters/techcorp",
  },
  {
    id: 84,
    name: "PLANET SPARK",
    logo: "/images/PLANET_SPARK.png",
    infoLink: "/recruiters/techcorp",
  },
  {
    id: 85,
    name: "RANE GROUP",
    logo: "/images/RANE_GROUP.png",
    infoLink: "/recruiters/techcorp",
  },
  {
    id: 86,
    name: "SUZUKI",
    logo: "/images/SUZUKI.png",
    infoLink: "/recruiters/techcorp",
  },
  {
    id: 58,
    name: "TATVASOFT",
    logo: "/images/TATVASOFT.png",
    infoLink: "/recruiters/techcorp",
  },
  {
    id: 88,
    name: "RESONANT",
    logo: "/images/RESONANT.png",
    infoLink: "/recruiters/techcorp",
  },
  {
    id: 89,
    name: "RKC",
    logo: "/images/RKC.png",
    infoLink: "/recruiters/techcorp",
  },
  {
    id: 90,
    name: "RSPL",
    logo: "/images/RSPL.png",
    infoLink: "/recruiters/techcorp",
  },
  {
    id: 91,
    name: "SABARAMATI GAS",
    logo: "/images/SABARAMATI_GAS.png",
    infoLink: "/recruiters/techcorp",
  },
  {
    id: 92,
    name: "SCHAFER",
    logo: "/images/SCHAFER.png",
    infoLink: "/recruiters/techcorp",
  },
  {
    id: 93,
    name: "SCHNEIDER ELECTRIC",
    logo: "/images/SCHNEIDER_ELECTRIC.png",
    infoLink: "/recruiters/techcorp",
  },
  {
    id: 94,
    name: "SGL",
    logo: "/images/SGL.png",
    infoLink: "/recruiters/techcorp",
  },
  {
    id: 95,
    name: "SHAPORORJI",
    logo: "/images/SHAPORORJI.png",
    infoLink: "/recruiters/techcorp",
  },
  {
    id: 96,
    name: "SHYAM",
    logo: "/images/SHYAM.png",
    infoLink: "/recruiters/techcorp",
  },
  {
    id: 97,
    name: "SIEMENS",
    logo: "/images/SIEMENS.png",
    infoLink: "/recruiters/techcorp",
  },
  {
    id: 98,
    name: "SILVERTOUCH",
    logo: "/images/SILVERTOUCH.png",
    infoLink: "/recruiters/techcorp",
  },
  {
    id: 99,
    name: "SIMFORM",
    logo: "/images/SIMFORM.png",
    infoLink: "/recruiters/techcorp",
  },
  {
    id: 100,
    name: "SITECH",
    logo: "/images/SITECH.png",
    infoLink: "/recruiters/techcorp",
  },
  {
    id: 101,
    name: "SMARTFILL",
    logo: "/images/SMARTFILL.png",
    infoLink: "/recruiters/techcorp",
  },
  {
    id: 102,
    name: "SMARTSENSE",
    logo: "/images/SMARTSENSE.png",
    infoLink: "/recruiters/techcorp",
  },
  {
    id: 103,
    name: "SUBLIME",
    logo: "/images/SUBLIME.png",
    infoLink: "/recruiters/techcorp",
  },

  {
    id: 105,
    name: "SWAPNA SHRUSHTI",
    logo: "/images/SWAPNA_SHRUSHTI.png",
    infoLink: "/recruiters/techcorp",
  },
  {
    id: 106,
    name: "SYNAPSE DESIGN",
    logo: "/images/SYNAPSE_DESIGN.png",
    infoLink: "/recruiters/techcorp",
  },
  {
    id: 107,
    name: "SYNOPTEK",
    logo: "/images/SYNOPTEK.png",
    infoLink: "/recruiters/techcorp",
  },
  {
    id: 108,
    name: "SYSTRA",
    logo: "/images/SYSTRA.png",
    infoLink: "/recruiters/techcorp",
  },
];
