const userData = {
  name: "John",
  surname: "Doe",
  father_name: "Michael Doe",
  dob: "1999-05-12",
  gender: "Male",
  degree: "ME",
  mobile_no: 9876543210,
  email: "john.doe@example.com",
  parent_email: "parent.doe@example.com",
  parent_mob: 9876543211,
  caste: "General",
  blood_group: "B+",
  physical_handicapped: false,
  height_cm: 175,
  weight_kg: 70,
  aadhar_no: "123412341234",
  aadhar_name: "John Doe",
  pan_no: "ABCDE1234F",
  pay_ref_no: "PAY12345",
};

const addressData = {
  perm_address: "123 Main Street",
  perm_city: "New York",
  perm_pin: 10001,
  perm_state: "New York",
  pres_address: "456 Secondary Street",
  pres_city: "Los Angeles",
  pres_pin: 90001,
};

const eductionData = {
  ssc_name: "ABC High School",
  ssc_board: "CBSE",
  ssc_passing_year: 2015,
  ssc_per: 85.5,
  ssc_cpi: 9.0,

  physics: "90",
  math: "95",
  chemistry: "88",
  total_mark: "450",
  obtain_mark: "400",
  gap_10_12: "0",
  hsc_board: "GSEB",
  hsc_passing_year: "2017",
  hsc_per: "85.5",
  hsc_cpi: "8.9",
  jee_percentile: "90",
  gujcet_score: "80",
  gujcet_physics: "75",
  gujcet_math: "85",
  gujcet_chem: "78",
  gujcet_percentile: "88",
  gujcet_total: "238",

  ddcet_score: "85",
  diploma_branch: "Computer Engineering",
  diploma_uni: "GTU",
  diploma_passing_year: "2020",
  gap_10_diploma: "0",
  diploma_cpi: "8.5",
  diploma_cgpa: "8.7",
  diploma_per: "85",
  diploma_dead_back: "0",
};

const graduationData = {
  admission_based_on: "Diploma",
  be_uni: "GTU",
  be_passing_year: "2024",
  be_branch: "Computer Engineering",
  be_sem1_spi: "8.5",
  be_sem2_spi: "8.7",
  be_sem3_spi: "8.6",
  be_sem4_spi: "8.9",
  be_sem5_spi: "8.8",
  be_sem6_spi: "8.9",
  be_sem7_spi: "9.0",
  be_sem8_spi: "9.1",
  be_cpi: "8.85",
  be_cgpa: "8.9",
  be_dead_back: "1",
  be_live_back: "0",
  be_total_back: "1",
  gap_12_dip_BE: "0",

  gate_score: "65",
  pgcet_score: "75",
  me_passing_year: "2026",
  me_branch: "Computer Science",
  me_specialization: "Artificial Intelligence",
  me_sem1_spi: "8.5",
  me_sem2_spi: "8.7",
  me_sem3_spi: "8.6",
  me_sem4_spi: "9.0",
  me_cpi: "8.8",
  me_dead_back: "0",
  me_live_back: "0",
  me_total_back: "0",
  gap_be_me: "1",

  ug_passing_year: "2021",
  ug_uni: "GTU",
  ug_sem1_per: "75",
  ug_sem2_per: "76",
  ug_sem3_per: "77",
  ug_sem4_per: "78",
  ug_sem5_per: "79",
  ug_sem6_per: "80",
  ug_sem7_per: "81",
  ug_sem8_per: "82",
  ug_per: "78.5",
  ug_dead_back: "1",
  ug_branch: "Computer Applications",
  gap_ug_pg: "0",
  gap_12_ug: "0",

  pg_passing_year: "2023",
  pg_sem1_spi: "8.2",
  pg_sem2_spi: "8.4",
  pg_sem3_spi: "8.6",
  pg_sem4_spi: "8.8",
  pg_cpi: "8.5",
  pg_live_back: "0",
  pg_dead_back: "0",
  pg_total_back: "0",
  pg_specialization: "Software Engineering",
};

export const userMainData = {
  userData,
  eductionData,
  addressData,
  graduationData,
};
